apiVersion: v1          # this uses the core API group (for basic objects like Services)
kind: Service           # this object type is a Service
metadata:
  name: nginx-service   # this is just the Service’s name
spec:
  type: NodePort        # means open a port on the node (EC2) so it’s accessible from outside
  selector:
    app: nginx          # matches Pods with label app=nginx (your two nginx Pods)
  ports:
    - port: 80          # port inside the cluster (service’s internal port)
      targetPort: 80    # port inside the Pod where nginx listens
      nodePort: 30080   # external port on the EC2 where you’ll connect from your browser
